import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Importando as fontes locais
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Configuração dos metadados usando a Metadata API
export const metadata: Metadata = {
  title: "Atualizar JSON",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Caminho do favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
